version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alexdb
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.15
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    networks:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
networks:
  postgres:
    driver: bridge

volumes:
  db-data:
  pgadmin-data: